"""Initial schema

Revision ID: 0a9b412fe3e6
Revises: 
Create Date: 2026-01-15 12:17:35.316396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a9b412fe3e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0停用 1正常)'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='超级权限(0否 1是)'),
    sa.Column('count', sa.Integer(), nullable=False, comment='计数'),
    sa.Column('score', sa.Float(), nullable=True, comment='分数'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='价格'),
    sa.Column('dept_id', sa.BigInteger(), nullable=True, comment='部门ID'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='开始时间'),
    sa.Column('last_login_time', sa.DateTime(timezone=True), nullable=True, comment='上次登录时间'),
    sa.Column('deleted', sa.Integer(), nullable=True, comment='逻辑删除'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='元数据 (JSONB，支持索引查询)'),
    sa.Column('config_json', sa.JSON(), nullable=True, comment='配置 (普通JSON)'),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='设置 (带默认值)'),
    sa.Column('large_data', sa.LargeBinary(), nullable=True, comment='大数据 (gzip压缩)'),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=True, comment='标签数组'),
    sa.Column('scores', postgresql.ARRAY(sa.Integer()), nullable=True, comment='分数数组'),
    sa.Column('salt', sa.LargeBinary(length=255), nullable=True, comment='加密盐(二进制)'),
    sa.Column('secret_key', sa.Text(), nullable=True, comment='密钥 (Fernet加密)'),
    sa.Column('api_token', sa.Text(), nullable=True, comment='API Token (Fernet加密)'),
    sa.Column('password_hash', sa.String(128), nullable=True, comment='密码 (SHA256哈希)'),
    sa.Column('phone', sa.String(256), nullable=True, comment='手机号 (读取时脱敏)'),
    sa.Column('id_card', sa.String(256), nullable=True, comment='身份证 (读取时脱敏)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('document_ids', postgresql.ARRAY(sa.Integer()), nullable=True, comment='关联文档ID列表'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    comment='演示表 - 展示各种字段类型'
    )
    op.create_index('idx_demo_document_ids_gin', 'demo', ['document_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_demo_metadata_gin', 'demo', ['metadata_json'], unique=False, postgresql_using='gin')
    op.create_index('idx_demo_tags_gin', 'demo', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_demo_id'), 'demo', ['id'], unique=True)
    op.create_index(op.f('ix_demo_status'), 'demo', ['status'], unique=False)
    op.create_table('demo_document',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('title', sa.String(length=256), nullable=False, comment='文档标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='文档内容'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='分类'),
    sa.Column('source', sa.String(length=128), nullable=True, comment='来源'),
    sa.Column('embedding', Vector(1024), nullable=True, comment='文档向量嵌入'),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True, comment='全文检索向量'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='文档元数据'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0停用 1正常)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除(0否 1是)'),
    sa.PrimaryKeyConstraint('id'),
    comment='文档表（PGVector 向量搜索）'
    )
    op.create_index('idx_demo_document_embedding_hnsw', 'demo_document', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_demo_document_tsv', 'demo_document', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_demo_document_category'), 'demo_document', ['category'], unique=False)
    op.create_index(op.f('ix_demo_document_deleted'), 'demo_document', ['deleted'], unique=False)
    op.create_index(op.f('ix_demo_document_id'), 'demo_document', ['id'], unique=True)
    op.create_index(op.f('ix_demo_document_status'), 'demo_document', ['status'], unique=False)
    op.create_table('demo_location',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='位置名称'),
    sa.Column('category', sa.String(length=64), nullable=False, comment='分类'),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, spatial_index=False), nullable=False, comment='地理位置点'),
    sa.Column('description', sa.Text(), nullable=True, comment='位置描述'),
    sa.Column('address', sa.String(length=256), nullable=True, comment='详细地址'),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展属性'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态(0停用 1正常)'),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除(0否 1是)'),
    sa.PrimaryKeyConstraint('id'),
    comment='位置表（PostGIS 空间数据）'
    )
    op.create_index('idx_demo_location_geom', 'demo_location', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_demo_location_category'), 'demo_location', ['category'], unique=False)
    op.create_index(op.f('ix_demo_location_deleted'), 'demo_location', ['deleted'], unique=False)
    op.create_index(op.f('ix_demo_location_id'), 'demo_location', ['id'], unique=True)
    op.create_index(op.f('ix_demo_location_status'), 'demo_location', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demo_location_status'), table_name='demo_location')
    op.drop_index(op.f('ix_demo_location_id'), table_name='demo_location')
    op.drop_index(op.f('ix_demo_location_deleted'), table_name='demo_location')
    op.drop_index(op.f('ix_demo_location_category'), table_name='demo_location')
    op.drop_index('idx_demo_location_geom', table_name='demo_location', postgresql_using='gist')
    op.drop_table('demo_location')
    op.drop_index(op.f('ix_demo_document_status'), table_name='demo_document')
    op.drop_index(op.f('ix_demo_document_id'), table_name='demo_document')
    op.drop_index(op.f('ix_demo_document_deleted'), table_name='demo_document')
    op.drop_index(op.f('ix_demo_document_category'), table_name='demo_document')
    op.drop_index('idx_demo_document_tsv', table_name='demo_document', postgresql_using='gin')
    op.drop_index('idx_demo_document_embedding_hnsw', table_name='demo_document', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('demo_document')
    op.drop_index(op.f('ix_demo_status'), table_name='demo')
    op.drop_index(op.f('ix_demo_id'), table_name='demo')
    op.drop_index('idx_demo_tags_gin', table_name='demo', postgresql_using='gin')
    op.drop_index('idx_demo_metadata_gin', table_name='demo', postgresql_using='gin')
    op.drop_index('idx_demo_document_ids_gin', table_name='demo', postgresql_using='gin')
    op.drop_table('demo')
    # ### end Alembic commands ###
