"""add ext to demo

Revision ID: e297599c34f0
Revises: 0a9b412fe3e6
Create Date: 2026-01-15 12:26:46.902836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e297599c34f0'
down_revision: Union[str, Sequence[str], None] = '0a9b412fe3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('ext', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展字段'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo', 'ext')
    # ### end Alembic commands ###
